spring:
  docker:
    compose:
      file: src/main/docker/compose.yaml
      enabled: true
      lifecycle-management: start_only

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/smartindus
    username: smartindus
    password: smartindus

  jpa:
    properties:
      hibernate:
        default_schema: public
        ddl-auto: update

  liquibase:
    change-log: db/changelog/master.yaml

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  # JWT Configuration
  jwt:
    secret-key: 3f+3wVmXQf4QCqaahmWBf/1Y9ysGnJsMImW4N7BJQDPqHtmWN8STm+S+7+7Jm0++EKd1y4Y/I8LNTly1ImSqKw==
    expiration: 86400000  # 24h en millisecondes