version: '3.8'
services:
  db:
    image: postgres:14
    container_name: smartindus-db
    environment:
      - POSTGRES_DB=smartindus
      - POSTGRES_USER=smartindus
      - POSTGRES_PASSWORD=smartindus
    ports:
      - "5432:5432"
    volumes:
      - smartindus-data:/var/lib/postgresql/data
    restart: always

  smartindus:
    image: smartindus:latest  # This refers to your locally built image
    container_name: smartindus
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/smartindus
      - SPRING_DATASOURCE_USERNAME=smartindus
      - SPRING_DATASOURCE_PASSWORD=smartindus
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8031:8031"  # Updated to match the port exposed in your Dockerfile
    depends_on:
      - db
    restart: always

volumes:
  smartindus-data: